In [1]:
import requests
import nltk
nltk.download('punkt')
nltk.download('wordnet')
from nltk import sent_tokenize, word_tokenize
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import stopwords
import pandas as pd
import numpy as np
import re   

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\VRAJ\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\VRAJ\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [2]:
Df_pd = pd.read_csv("C:/Users/VRAJ/Desktop/ml/Scrape_AmazonReviews/Scrape_AmazonReviews/spiders/output.csv")
Df_pd

Name                                              Title  \
0                   Dimpy  \n\n\n\n\n\n\n\n  \n  \n    Without a doubt a ...   
1         Amazon Customer  \n\n\n\n\n\n\n\n  \n  \n    Must buy this book...   
2    Pratap Bhattacharyya  \n\n\n\n\n\n\n\n  \n  \n    About the Product\...   
3                  Sawita  \n\n\n\n\n\n\n\n  \n  \n    Intriguing read fo...   
4             Ravi Garlay  \n\n\n\n\n\n\n\n  \n  \n    The best book for ...   
..                    ...                                                ...   
801                Manish             \n\n\n\n\n\n\n\n  \n  \n    Good\n  \n   
802    Dr. Sandeep Amgoth        \n\n\n\n\n\n\n\n  \n  \n    Nice book\n  \n   
803       Kindle Customer  \n\n\n\n\n\n\n\n  \n  \n    The entrance  of c...   
804        Ketan S Thakur        \n\n\n\n\n\n\n\n  \n  \n    Good book\n  \n   
805         Chirag Sharma  \n\n\n\n\n\n\n\n  \n  \n    Condition was not ...   

                 Rating                                            Comment  
0    5.0 out of 5 stars  \n\n\n\n\n\n\n\n  \n  \n    "What did God do b...  
1    5.0 out of 5 stars  \n\n\n\n\n\n\n\n  \n  \n    A very good book.T...  
2    5.0 out of 5 stars  \n\n\n\n\n\n\n\n  \n  \n    There is no compar...  
3    5.0 out of 5 stars  \n\n\n\n\n\n\n\n  \n  \n    A brief history of...  
4    5.0 out of 5 stars  \n\n\n\n\n\n\n\n  \n  \n    This book is reall...  
..                  ...                                                ...  
801  5.0 out of 5 stars             \n\n\n\n\n\n\n\n  \n  \n    Good\n  \n  
802  4.0 out of 5 stars             \n\n\n\n\n\n\n\n  \n  \n    Nice\n  \n  
803  5.0 out of 5 stars  \n\n\n\n\n\n\n\n  \n  \n    It is the first bo...  
804  3.0 out of 5 stars        \n\n\n\n\n\n\n\n  \n  \n    Good book\n  \n  
805  3.0 out of 5 stars   \n\n\n\n\n\n\n\n  \n  \n    Excellent book\n  \n  

[806 rows x 4 columns]

In [3]:
Rev_list = Df_pd["Comment"]

In [4]:
def preprocess(text):
    clean_data = []
    for x in (text[:]): 
        new_text = re.sub('<.*?>', '', x)   # remove HTML tags
        new_text = re.sub(r'[^\w\s]', '', new_text) # remove punc.
        new_text = re.sub(r'\d+','',new_text)# remove numbers
        new_text = new_text.lower() # lower case, .upper() for upper          
        if new_text != '':
            clean_data.append(new_text)
    return clean_data

In [5]:
def tokenization_w(words):
    w_new = []
    for w in (words[:]):
        w_token = word_tokenize(w)
        if w_token != '':
            w_new.append(w_token)
    return w_new

In [6]:
lemmatizer = WordNetLemmatizer()
def lemmatization(words):
    new = []
    for i in range(len(Rev_list)):
        lem_words = [lemmatizer.lemmatize(x) for x in (words[:][i])]
        new.append(lem_words)
    return new

In [7]:
clean_list = preprocess(Rev_list) #removes punctuation, see above
clean_words = tokenization_w(clean_list) # word tokenization
lem = lemmatization(clean_words)
lem

[['what',
  'did',
  'god',
  'do',
  'before',
  'he',
  'created',
  'the',
  'universe',
  'augustine',
  'didnt',
  'reply',
  'he',
  'wa',
  'preparing',
  'hell',
  'for',
  'people',
  'who',
  'asked',
  'such',
  'question',
  'instead',
  'he',
  'said',
  'that',
  'time',
  'wa',
  'a',
  'property',
  'of',
  'the',
  'universe',
  'that',
  'god',
  'created',
  'and',
  'that',
  'time',
  'did',
  'not',
  'exist',
  'before',
  'the',
  'beginning',
  'of',
  'the',
  'universestephen',
  'hawking',
  'take',
  'u',
  'on',
  'a',
  'journey',
  'from',
  'the',
  'time',
  'when',
  'the',
  'world',
  'believed',
  'that',
  'earth',
  'wa',
  'the',
  'center',
  'of',
  'the',
  'universe',
  'and',
  'supported',
  'on',
  'the',
  'back',
  'of',
  'a',
  'giant',
  'tortoise',
  'to',
  'our',
  'age',
  'when',
  'we',
  'know',
  'better',
  'without',
  'the',
  'use',
  'of',
  'any',
  'mathematical',
  'equation',
  'except',
  'the',
  'one',
  'famous',

In [8]:
new_review = []
for i in lem:
    new_review.append(" ".join(i))
new_review

['what did god do before he created the universe augustine didnt reply he wa preparing hell for people who asked such question instead he said that time wa a property of the universe that god created and that time did not exist before the beginning of the universestephen hawking take u on a journey from the time when the world believed that earth wa the center of the universe and supported on the back of a giant tortoise to our age when we know better without the use of any mathematical equation except the one famous mass energy equivalence relation by einstein he ha explained the nature of our universe from the smallest particle which can not be seen to the biggest entity the black hole in a simple languagethe manner in which hawking broke down complex concept in theoretical physic along with his adept use of humor he clearly won over the reader who otherwise might have found themselves intimidated by physic and mathsi recommend it to all people who are interested in physic and cosmol

In [9]:
data = pd.DataFrame({'review':new_review})
data['review']

0      what did god do before he created the universe...
1      a very good bookthis book is like a treeyou ca...
2      there is no comparison of this book from the b...
3      a brief history of time what a fascinating boo...
4      this book is really a proof that why wa stephe...
                             ...                        
801                                                 good
802                                                 nice
803    it is the first book written by stephen hawkin...
804                                            good book
805                                       excellent book
Name: review, Length: 806, dtype: object

In [10]:
data['word_count'] = data['review'].apply(lambda x: len(str(x).split(" ")))
data[['review','word_count']].head()

review  word_count
0  what did god do before he created the universe...         180
1  a very good bookthis book is like a treeyou ca...          70
2  there is no comparison of this book from the b...          56
3  a brief history of time what a fascinating boo...         162
4  this book is really a proof that why wa stephe...         106

In [11]:
data['char_count'] = data['review'].str.len() ## this also includes spaces
data[['review','char_count']].head()

review  char_count
0  what did god do before he created the universe...        1019
1  a very good bookthis book is like a treeyou ca...         362
2  there is no comparison of this book from the b...         314
3  a brief history of time what a fascinating boo...         915
4  this book is really a proof that why wa stephe...         577

In [12]:
#Average Word Length
#Number of characters(without space count)/Total number of words
def avg_word(sentence):
  words = sentence.split()
  print(words)
  print(len(words))
  print(sum(len(word) for word in words))
  if words == []:
    return 0
  return (sum(len(word) for word in words)/len(words))

data['avg_word'] = data['review'].apply(lambda x: avg_word(x))
data[['review','avg_word']].head()

['what', 'did', 'god', 'do', 'before', 'he', 'created', 'the', 'universe', 'augustine', 'didnt', 'reply', 'he', 'wa', 'preparing', 'hell', 'for', 'people', 'who', 'asked', 'such', 'question', 'instead', 'he', 'said', 'that', 'time', 'wa', 'a', 'property', 'of', 'the', 'universe', 'that', 'god', 'created', 'and', 'that', 'time', 'did', 'not', 'exist', 'before', 'the', 'beginning', 'of', 'the', 'universestephen', 'hawking', 'take', 'u', 'on', 'a', 'journey', 'from', 'the', 'time', 'when', 'the', 'world', 'believed', 'that', 'earth', 'wa', 'the', 'center', 'of', 'the', 'universe', 'and', 'supported', 'on', 'the', 'back', 'of', 'a', 'giant', 'tortoise', 'to', 'our', 'age', 'when', 'we', 'know', 'better', 'without', 'the', 'use', 'of', 'any', 'mathematical', 'equation', 'except', 'the', 'one', 'famous', 'mass', 'energy', 'equivalence', 'relation', 'by', 'einstein', 'he', 'ha', 'explained', 'the', 'nature', 'of', 'our', 'universe', 'from', 'the', 'smallest', 'particle', 'which', 'can', 'not'

['a', 'good', 'printed', 'copy', 'reading', 'the', 'book', 'is', 'a', 'good', 'experience', 'it', 'is', 'a', 'time', 'travel', 'with', 'nobel', 'laureate', 'the', 'genius', 'stephen', 'hawking', 'it', 'is', 'explained', 'in', 'a', 'lucid', 'teaching', 'style', 'it', 'is', 'a', 'time', 'travel', 'with', 'the', 'greatest', 'astrophysicist', 'in', 'history', 'explaining', 'the', 'evolution', 'of', 'science', 'it', 'is', 'good', 'for', 'student', 'science', 'enthusiast', 'it', 'summarises', 'all', 'the', 'important', 'achievement', 'in', 'science', 'in', 'nutshell', 'upto', 'the', 'time', 'of', 'writing', 'of', 'this', 'book', 'and', 'cap', 'it', 'with', 'the', 'author', 'finding', 'too']
80
373
['what', 'do', 'we', 'know', 'about', 'the', 'universe', 'how', 'do', 'we', 'know', 'what', 'we', 'know', 'where', 'did', 'the', 'universe', 'come', 'from', 'and', 'where', 'is', 'it', 'going', 'what', 'is', 'the', 'nature', 'of', 'time', 'did', 'time', 'have', 'a', 'beginning', 'will', 'it', 'ever

review  avg_word
0  what did god do before he created the universe...  4.666667
1  a very good bookthis book is like a treeyou ca...  4.185714
2  there is no comparison of this book from the b...  4.625000
3  a brief history of time what a fascinating boo...  4.654321
4  this book is really a proof that why wa stephe...  4.452830

In [13]:
#Number of stopwords
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')

data['stopwords'] = data['review'].apply(lambda x: len([x for x in x.split() if x in stop]))
data[['review','stopwords']].head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\VRAJ\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


review  stopwords
0  what did god do before he created the universe...         87
1  a very good bookthis book is like a treeyou ca...         38
2  there is no comparison of this book from the b...         28
3  a brief history of time what a fascinating boo...         79
4  this book is really a proof that why wa stephe...         50

In [14]:
#Number of special characters
data['hastags'] = data['review'].apply(lambda x: len([x for x in x.split() if x.startswith('#')]))
data[['review','hastags']].head()

review  hastags
0  what did god do before he created the universe...        0
1  a very good bookthis book is like a treeyou ca...        0
2  there is no comparison of this book from the b...        0
3  a brief history of time what a fascinating boo...        0
4  this book is really a proof that why wa stephe...        0

In [15]:
#Number of numerics
data['numerics'] = data['review'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))
data[['review','numerics']].head()

review  numerics
0  what did god do before he created the universe...         0
1  a very good bookthis book is like a treeyou ca...         0
2  there is no comparison of this book from the b...         0
3  a brief history of time what a fascinating boo...         0
4  this book is really a proof that why wa stephe...         0

In [16]:
#Number of Uppercase words
data['upper'] = data['review'].apply(lambda x: len([x for x in x.split() if x.isupper()]))
data[['review','upper']].head()

review  upper
0  what did god do before he created the universe...      0
1  a very good bookthis book is like a treeyou ca...      0
2  there is no comparison of this book from the b...      0
3  a brief history of time what a fascinating boo...      0
4  this book is really a proof that why wa stephe...      0

In [17]:
pos_family = {
    'noun' : ['NN','NNS','NNP','NNPS'],
    'pron' : ['PRP','PRP$','WP','WP$'],
    'verb' : ['VB','VBD','VBG','VBN','VBP','VBZ'],
    'adj' :  ['JJ','JJR','JJS'],
    'adv' : ['RB','RBR','RBS','WRB']
}

# function to check and get the part of speech tag count of a words in a given sentence
from textblob import TextBlob, Word, Blobber
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
def check_pos_tag(x, flag):
    cnt = 0
    try:
        wiki = TextBlob(x)
        for tup in wiki.tags:
            ppo = list(tup)[1]
            if ppo in pos_family[flag]:
                cnt += 1
                print(ppo, tup)
    except:
        pass
    return cnt

data['noun_count'] = data['review'].apply(lambda x: check_pos_tag(x, 'noun'))
data['verb_count'] = data['review'].apply(lambda x: check_pos_tag(x, 'verb'))
data['adj_count'] = data['review'].apply(lambda x: check_pos_tag(x, 'adj'))
data['adv_count'] = data['review'].apply(lambda x: check_pos_tag(x, 'adv'))
data['pron_count'] = data['review'].apply(lambda x: check_pos_tag(x, 'pron'))
data[['review','noun_count','verb_count','adj_count', 'adv_count', 'pron_count' ]].head()


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\VRAJ\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\VRAJ\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


NN ('augustine', 'NN')
NN ('didnt', 'NN')
NN ('reply', 'NN')
NN ('hell', 'NN')
NNS ('people', 'NNS')
NN ('question', 'NN')
NN ('time', 'NN')
NN ('property', 'NN')
NN ('universe', 'NN')
NN ('god', 'NN')
NN ('time', 'NN')
NN ('beginning', 'NN')
NN ('u', 'NN')
NN ('journey', 'NN')
NN ('time', 'NN')
NN ('world', 'NN')
NN ('earth', 'NN')
NN ('center', 'NN')
NN ('universe', 'NN')
NN ('back', 'NN')
NN ('tortoise', 'NN')
NN ('age', 'NN')
NN ('use', 'NN')
NN ('equation', 'NN')
NN ('mass', 'NN')
NN ('energy', 'NN')
NN ('equivalence', 'NN')
NN ('relation', 'NN')
NN ('einstein', 'NN')
NN ('nature', 'NN')
NN ('universe', 'NN')
NN ('particle', 'NN')
NN ('entity', 'NN')
NN ('hole', 'NN')
NN ('languagethe', 'NN')
NN ('manner', 'NN')
NN ('concept', 'NN')
NNS ('physic', 'NNS')
NN ('adept', 'NN')
NN ('use', 'NN')
NN ('humor', 'NN')
NN ('reader', 'NN')
NNS ('people', 'NNS')
NN ('cosmology', 'NN')
NN ('equation', 'NN')
NN ('bookthis', 'NN')
NN ('book', 'NN')
NN ('treeyou', 'NN')
NN ('tree', 'NN')
NN ('top'

NN ('scientist', 'NN')
NN ('death', 'NN')
NN ('loss', 'NN')
NN ('world', 'NN')
NN ('book', 'NN')
NN ('youre', 'NN')
NNS ('atrophysics', 'NNS')
NN ('book', 'NN')
NN ('hawking', 'NN')
NN ('thing', 'NN')
NN ('detail', 'NN')
NN ('pricing', 'NN')
NN ('condition', 'NN')
NN ('option', 'NN')
NN ('gift', 'NN')
NNS ('kidsstudents', 'NNS')
NN ('science', 'NN')
NN ('i', 'NN')
NN ('book', 'NN')
NN ('one', 'NN')
NN ('cosmology', 'NN')
NN ('book', 'NN')
NN ('explanation', 'NN')
NN ('manner', 'NN')
NN ('everything', 'NN')
NN ('space', 'NN')
NN ('book', 'NN')
NN ('achievement', 'NN')
NN ('mankindquantum', 'NN')
NN ('mechanic', 'NN')
NN ('scientist', 'NN')
NN ('style', 'NN')
NN ('physicsdaddy', 'NN')
NN ('spaceride', 'NN')
NN ('i', 'NN')
NN ('book', 'NN')
NN ('book', 'NN')
NN ('kind', 'NN')
NN ('possession', 'NN')
NN ('scientist', 'NN')
NN ('millennium', 'NN')
NN ('set', 'NN')
NN ('readingsrequire', 'NN')
NN ('mental', 'NN')
NN ('involvement', 'NN')
NN ('stephen', 'NN')
NN ('path', 'NN')
NN ('history', 

NN ('book', 'NN')
NN ('cross', 'NN')
NN ('word', 'NN')
NN ('andfont', 'NN')
NN ('size', 'NN')
NN ('quality', 'NN')
NN ('print', 'NN')
NN ('need', 'NN')
NN ('review', 'NN')
NN ('book', 'NN')
NN ('book', 'NN')
NN ('space', 'NN')
NN ('loverbantam', 'NN')
NN ('publication', 'NN')
NN ('print', 'NN')
NN ('book', 'NN')
NN ('astronomy', 'NN')
NN ('cosmology', 'NN')
NN ('book', 'NN')
NN ('stephen', 'NN')
NN ('everything', 'NN')
NN ('everything', 'NN')
NN ('quantum', 'NN')
NN ('mechanic', 'NN')
NN ('unification', 'NN')
NN ('book', 'NN')
NN ('copy', 'NN')
NN ('story', 'NN')
NN ('time', 'NN')
NN ('understanding', 'NN')
NN ('i', 'NN')
NN ('collection', 'NN')
NN ('book', 'NN')
NN ('price', 'NN')
NN ('delivery', 'NN')
NN ('india', 'NN')
NN ('time', 'NN')
NN ('stephen', 'NN')
NN ('workthis', 'NN')
NN ('book', 'NN')
NN ('everything', 'NN')
NN ('hole', 'NN')
NN ('time', 'NN')
NN ('book', 'NN')
NN ('book', 'NN')
NN ('time', 'NN')
NN ('everyone', 'NN')
NN ('author', 'NN')
NN ('time', 'NN')
NN ('idk', 'NN'

NN ('book', 'NN')
NN ('revision', 'NN')
NN ('student', 'NN')
NN ('book', 'NN')
NN ('book', 'NN')
NN ('packet', 'NN')
NN ('thing', 'NN')
NN ('page', 'NN')
NN ('dont', 'NN')
NN ('buy', 'NN')
NN ('nothing', 'NN')
NN ('i', 'NN')
NN ('surfacea', 'NN')
NN ('comparision', 'NN')
NN ('product', 'NN')
NN ('book', 'NN')
NN ('everyone', 'NN')
NN ('selling', 'NN')
NN ('reason', 'NN')
NN ('book', 'NN')
NN ('book', 'NN')
NN ('simple', 'NN')
NN ('everyone', 'NN')
NN ('book', 'NN')
NN ('stephen', 'NN')
NN ('book', 'NN')
NN ('readablei', 'NN')
NN ('book', 'NN')
NN ('scientist', 'NN')
NN ('book', 'NN')
NN ('science', 'NN')
NN ('student', 'NN')
NN ('book', 'NN')
NN ('book', 'NN')
NN ('languagea', 'NN')
NN ('person', 'NN')
NN ('idea', 'NN')
NN ('space', 'NN')
NN ('book', 'NN')
NN ('paper', 'NN')
NN ('quality', 'NN')
NN ('picture', 'NN')
NN ('specification', 'NN')
NN ('printing', 'NN')
NN ('page', 'NN')
NN ('price', 'NN')
NN ('book', 'NN')
NN ('book', 'NN')
NN ('layman', 'NN')
NN ('masterpiece', 'NN')
NN ('

NN ('book', 'NN')
NN ('history', 'NN')
NN ('time', 'NN')
NN ('book', 'NN')
NN ('exploration', 'NN')
NN ('experience', 'NN')
NN ('price', 'NN')
NN ('booksty', 'NN')
NN ('amazon', 'NN')
NN ('genius', 'NN')
NN ('work', 'NN')
NN ('geniusmust', 'NN')
NN ('everyone', 'NN')
NN ('poweress', 'NN')
NN ('paper', 'NN')
NN ('quality', 'NN')
NN ('superb', 'NN')
NN ('awesome', 'NN')
NN ('book', 'NN')
NN ('i', 'NN')
NN ('readvery', 'NN')
NN ('go', 'NN')
NN ('book', 'NN')
NN ('time', 'NN')
NN ('delivery', 'NN')
NN ('amazonpaper', 'NN')
NN ('quality', 'NN')
NN ('sir', 'NN')
NN ('i', 'NN')
NN ('product', 'NN')
NN ('amazon', 'NN')
NNS ('i', 'NNS')
NN ('advance', 'NN')
NN ('product', 'NN')
NN ('help', 'NN')
NN ('book', 'NN')
NN ('length', 'NN')
NN ('book', 'NN')
NN ('book', 'NN')
NN ('page', 'NN')
NN ('interest', 'NN')
NN ('print', 'NN')
NN ('quality', 'NN')
NN ('promotion', 'NN')
NN ('material', 'NN')
NN ('wa', 'NN')
NN ('book', 'NN')
NN ('anybody', 'NN')
NN ('field', 'NN')
NN ('science', 'NN')
NN ('print

NN ('read', 'NN')
NN ('scientist', 'NN')
NN ('time', 'NN')
NN ('book', 'NN')
NN ('dont', 'NN')
NN ('anything', 'NN')
NN ('lot', 'NN')
NN ('picture', 'NN')
NN ('figure', 'NN')
NN ('content', 'NN')
NN ('way', 'NN')
NN ('mind', 'NN')
NN ('image', 'NN')
NN ('universe', 'NN')
NN ('step', 'NN')
NN ('mystery', 'NN')
NN ('universe', 'NN')
NN ('chapter', 'NN')
NN ('chapter', 'NN')
NN ('science', 'NN')
NN ('knowledge', 'NN')
NN ('term', 'NN')
NN ('i', 'NN')
NN ('science', 'NN')
NN ('book', 'NN')
NN ('mind', 'NN')
NN ('exposure', 'NN')
NN ('space', 'NN')
NN ('author', 'NN')
NN ('ha', 'NN')
NN ('concept', 'NN')
NNS ('physic', 'NNS')
NN ('layman', 'NN')
NN ('part', 'NN')
NN ('read', 'NN')
NN ('universe', 'NN')
NN ('hole', 'NN')
NN ('book', 'NN')
NN ('reader', 'NN')
NN ('world', 'NN')
NN ('way', 'NN')
NNS ('earthit', 'NNS')
NN ('thing', 'NN')
NN ('feel', 'NN')
NNS ('tiny', 'NNS')
NN ('respect', 'NN')
NN ('work', 'NN')
NN ('scientist', 'NN')
NN ('understanding', 'NN')
NN ('drhawking', 'NN')
NN ('ha',

NN ('book', 'NN')
NNS ('enthuestics', 'NNS')
NNS ('people', 'NNS')
NN ('stephen', 'NN')
NN ('physic', 'NN')
NN ('universe', 'NN')
NNS ('thanks', 'NNS')
NN ('delevery', 'NN')
NN ('i', 'NN')
NN ('ok', 'NN')
NN ('reading', 'NN')
NN ('book', 'NN')
NN ('space', 'NN')
NN ('book', 'NN')
NN ('everything', 'NN')
NN ('universe', 'NN')
NN ('bind', 'NN')
NN ('book', 'NN')
NN ('time', 'NN')
NN ('i', 'NN')
NN ('book', 'NN')
NN ('date', 'NN')
NN ('paper', 'NN')
NN ('quality', 'NN')
NN ('print', 'NN')
NN ('quality', 'NN')
NN ('brain', 'NN')
NN ('book', 'NN')
NN ('physic', 'NN')
NN ('book', 'NN')
NN ('i', 'NN')
NN ('book', 'NN')
NN ('mark', 'NN')
NNS ('i', 'NNS')
NN ('book', 'NN')
NN ('dam', 'NN')
NN ('gr', 'NN')
NN ('book', 'NN')
NN ('book', 'NN')
NN ('i', 'NN')
NN ('detail', 'NN')
NN ('stephen', 'NN')
NN ('book', 'NN')
NN ('super', 'NN')
NN ('i', 'NN')
NN ('i', 'NN')
NN ('account', 'NN')
NN ('please', 'NN')
NN ('money', 'NN')
NN ('i', 'NN')
NN ('book', 'NN')
NN ('condition', 'NN')
NN ('book', 'NN')
N

NN ('start', 'NN')
NN ('book', 'NN')
NN ('beginner', 'NN')
NN ('nothing', 'NN')
NNS ('astrophysics', 'NNS')
NN ('physic', 'NN')
NN ('youre', 'NN')
NN ('book', 'NN')
NN ('book', 'NN')
NN ('book', 'NN')
NNS ('people', 'NNS')
NN ('science', 'NN')
NN ('i', 'NN')
NN ('thing', 'NN')
NN ('book', 'NN')
NN ('i', 'NN')
NN ('brilliant', 'NN')
NN ('masterpiece', 'NN')
NN ('mind', 'NN')
NN ('i', 'NN')
NN ('prof', 'NN')
NN ('hawking', 'NN')
NN ('work', 'NN')
NN ('book', 'NN')
NN ('exception', 'NN')
NN ('book', 'NN')
NN ('i', 'NN')
NN ('issue', 'NN')
NN ('fall', 'NN')
NN ('asleep', 'NN')
NN ('i', 'NN')
NN ('book', 'NN')
NN ('couple', 'NN')
NN ('page', 'NN')
NN ('money', 'NN')
NN ('star', 'NN')
NN ('dont', 'NN')
NN ('understand', 'NN')
NN ('anything', 'NN')
NN ('bit', 'NN')
NN ('world', 'NN')
NN ('start', 'NN')
NN ('book', 'NN')
NN ('science', 'NN')
NN ('peoplemost', 'NN')
NN ('book', 'NN')
NN ('book', 'NN')
NN ('stephen', 'NN')
NN ('review', 'NN')
NN ('everyone', 'NN')
NN ('cant', 'NN')
NN ('book', '

VBZ ('is', 'VBZ')
VBP ('think', 'VBP')
VB ('have', 'VB')
VBN ('simplified', 'VBN')
VBG ('keeping', 'VBG')
VBN ('engaged', 'VBN')
VBG ('making', 'VBG')
VBP ('wouldnt', 'VBP')
VBP ('have', 'VBP')
VBG ('reminding', 'VBG')
VBZ ('is', 'VBZ')
VBP ('wa', 'VBP')
VBG ('hawking', 'VBG')
VBP ('mean', 'VBP')
VBZ ('explains', 'VBZ')
VB ('understand', 'VB')
VB ('understand', 'VB')
VBZ ('is', 'VBZ')
VBZ ('add', 'VBZ')
VBP ('are', 'VBP')
VBZ ('is', 'VBZ')
VBZ ('is', 'VBZ')
VBP ('cant', 'VBP')
VB ('put', 'VB')
VBP ('start', 'VBP')
VBG ('reading', 'VBG')
VBP ('make', 'VBP')
VBP ('understand', 'VBP')
VBZ ('inspires', 'VBZ')
VB ('thinkwhich', 'VB')
VBP ('find', 'VBP')
VBZ ('is', 'VBZ')
VBG ('writing', 'VBG')
VBN ('informed', 'VBN')
VBG ('smspackaging', 'VBG')
VBN ('packed', 'VBN')
VBD ('corrugated', 'VBD')
VB ('carry', 'VB')
VBZ ('is', 'VBZ')
VBN ('expected', 'VBN')
VBP ('are', 'VBP')
VBG ('coating', 'VBG')
VBZ ('is', 'VBZ')
VB ('understand', 'VB')
VB ('be', 'VB')
VB ('read', 'VB')
VBZ ('is', 'VBZ')
VBD (

VBP ('love', 'VBP')
VBZ ('is', 'VBZ')
VB ('know', 'VB')
VBZ ('is', 'VBZ')
VBZ ('stephen', 'VBZ')
VBG ('hawking', 'VBG')
VBD ('recommended', 'VBD')
VBG ('looking', 'VBG')
VBG ('doing', 'VBG')
VBG ('providing', 'VBG')
VBZ ('is', 'VBZ')
VBN ('written', 'VBN')
VBZ ('is', 'VBZ')
VB ('understand', 'VB')
VBZ ('is', 'VBZ')
VBG ('interesting', 'VBG')
VB ('read', 'VB')
VBD ('found', 'VBD')
VBG ('interesting', 'VBG')
VB ('read', 'VB')
VBP ('know', 'VBP')
VBZ ('is', 'VBZ')
VBP ('read', 'VBP')
VBP ('want', 'VBP')
VB ('read', 'VB')
VBZ ('is', 'VBZ')
VBN ('written', 'VBN')
VBG ('hawking', 'VBG')
VBD ('made', 'VBD')
VBZ ('is', 'VBZ')
VBZ ('is', 'VBZ')
VBZ ('is', 'VBZ')
VBN ('reduced', 'VBN')
VBD ('received', 'VBD')
VBN ('pirated', 'VBN')
VBN ('sold', 'VBN')
VBZ ('is', 'VBZ')
VBG ('returning', 'VBG')
VBD ('got', 'VBD')
VBD ('complicated', 'VBD')
VBN ('explained', 'VBN')
VB ('be', 'VB')
VBN ('remembered', 'VBN')
VB ('understand', 'VB')
VBN ('made', 'VBN')
VBP ('want', 'VBP')
VB ('understand', 'VB')
VBZ 

VBP ('are', 'VBP')
VBG ('missing', 'VBG')
VBG ('reading', 'VBG')
VBZ ('i', 'VBZ')
VBP ('feel', 'VBP')
VBD ('knew', 'VBD')
VBP ('wa', 'VBP')
VBG ('scratching', 'VBG')
VB ('read', 'VB')
VBG ('being', 'VBG')
VB ('readthis', 'VB')
VBZ ('is', 'VBZ')
VBZ ('is', 'VBZ')
VBN ('written', 'VBN')
VBP ('understand', 'VBP')
VBG ('hawking', 'VBG')
VBP ('are', 'VBP')
VB ('read', 'VB')
VB ('read', 'VB')
VBZ ('is', 'VBZ')
VBN ('written', 'VBN')
VBG ('having', 'VBG')
VB ('understand', 'VB')
VBZ ('is', 'VBZ')
VBP ('ant', 'VBP')
VBN ('written', 'VBN')
VBG ('amazing', 'VBG')
VBZ ('is', 'VBZ')
VBG ('considering', 'VBG')
VBP ('read', 'VBP')
VBZ ('is', 'VBZ')
VBN ('beginnersloved', 'VBN')
VBG ('amazonwaiting', 'VBG')
VB ('sum', 'VB')
VBD ('missed', 'VBD')
VBZ ('wa', 'VBZ')
VB ('happen', 'VB')
VBG ('charging', 'VBG')
VB ('r', 'VB')
VB ('have', 'VB')
VBN ('exceeded', 'VBN')
VBD ('liked', 'VBD')
VBN ('written', 'VBN')
VBP ('love', 'VBP')
VBZ ('is', 'VBZ')
VBP ('feel', 'VBP')
VBG ('opening', 'VBG')
VB ('read', 'VB

VBP ('suggest', 'VBP')
VBD ('ha', 'VBD')
VBD ('studied', 'VBD')
VB ('read', 'VB')
VBZ ('is', 'VBZ')
VB ('put', 'VB')
VBN ('written', 'VBN')
VBZ ('is', 'VBZ')
VB ('read', 'VB')
VBZ ('is', 'VBZ')
VBG ('assuming', 'VBG')
VBP ('know', 'VBP')
VBD ('started', 'VBD')
VBD ('created', 'VBD')
VBP ('see', 'VBP')
VBZ ('i', 'VBZ')
VBP ('wa', 'VBP')
VBN ('interested', 'VBN')
VB ('get', 'VB')
VBZ ('explains', 'VBZ')
VBZ ('is', 'VBZ')
VBG ('expressing', 'VBG')
VBZ ('wa', 'VBZ')
VB ('trust', 'VB')
VBP ('continue', 'VBP')
VB ('read', 'VB')
VBG ('worrying', 'VBG')
VB ('get', 'VB')
VBP ('astrophysicist', 'VBP')
VBP ('ha', 'VBP')
VBN ('been', 'VBN')
VBN ('worked', 'VBN')
VBN ('found', 'VBN')
VBG ('proving', 'VBG')
VB ('i', 'VB')
VBD ('had', 'VBD')
VBG ('reading', 'VBG')
VB ('recommend', 'VB')
VB ('recommend', 'VB')
VB ('read', 'VB')
VB ('help', 'VB')
VB ('get', 'VB')
VBD ('discussed', 'VBD')
VBZ ('listen', 'VBZ')
VBZ ('is', 'VBZ')
VBP ('are', 'VBP')
VBG ('mindboggling', 'VBG')
VBD ('aid', 'VBD')
VBG ('unde

VB ('read', 'VB')
VBP ('didnot', 'VBP')
VB ('get', 'VB')
VBP ('have', 'VBP')
VBN ('brought', 'VBN')
VBP ('have', 'VBP')
VB ('read', 'VB')
VB ('cover', 'VB')
VBG ('hawking', 'VBG')
VB ('i', 'VB')
VB ('say', 'VB')
VB ('go', 'VB')
VBD ('bought', 'VBD')
VBD ('dont', 'VBD')
VBP ('have', 'VBP')
VB ('refund', 'VB')
VBZ ('is', 'VBZ')
VBP ('read', 'VBP')
VBD ('got', 'VBD')
VBZ ('is', 'VBZ')
VBD ('received', 'VBD')
VBZ ('is', 'VBZ')
VBP ('know', 'VBP')
VBG ('hawking', 'VBG')
VB ('read', 'VB')
VBP ('want', 'VBP')
VB ('say', 'VB')
VBZ ('is', 'VBZ')
VBG ('hawking', 'VBG')
VBD ('explained', 'VBD')
VBD ('aroused', 'VBD')
VBG ('reading', 'VBG')
VBP ('want', 'VBP')
VB ('return', 'VB')
VB ('say', 'VB')
VBZ ('is', 'VBZ')
VBZ ('is', 'VBZ')
VBZ ('is', 'VBZ')
VBD ('hoped', 'VBD')
VBG ('betterpackaging', 'VBG')
VBP ('provide', 'VBP')
VB ('be', 'VB')
VBZ ('stephen', 'VBZ')
VBG ('hawking', 'VBG')
VB ('read', 'VB')
VBP ('have', 'VBP')
VBN ('been', 'VBN')
VBZ ('explains', 'VBZ')
VBP ('are', 'VBP')
VBP ('are', 'V

VB ('read', 'VB')
VB ('start', 'VB')
VBG ('looking', 'VBG')
VB ('finish', 'VB')
VBN ('packed', 'VBN')
VBD ('answered', 'VBD')
VBN ('celebrated', 'VBN')
VBD ('william', 'VBD')
VBG ('hawking', 'VBG')
VBG ('leading', 'VBG')
VBZ ('is', 'VBZ')
VBZ ('explains', 'VBZ')
VB ('try', 'VB')
VB ('dig', 'VB')
VB ('try', 'VB')
VB ('explain', 'VB')
VBN ('abbreviated', 'VBN')
VB ('toe', 'VB')
VBZ ('is', 'VBZ')
VBN ('written', 'VBN')
VBP ('wa', 'VBP')
VBG ('hawking', 'VBG')
VBN ('lost', 'VBN')
VBD ('said', 'VBD')
VB ('find', 'VB')
VBZ ('is', 'VBZ')
VBN ('supposed', 'VBN')
VB ('be', 'VB')
VBP ('give', 'VBP')
VB ('make', 'VB')
VB ('behave', 'VB')
VBZ ('doe', 'VBZ')
VBZ ('ha', 'VBZ')
VBD ('found', 'VBD')
VBZ ('particle', 'VBZ')
VBD ('found', 'VBD')
VBD ('found', 'VBD')
VBD ('wa', 'VBD')
VBZ ('exists', 'VBZ')
VBP ('know', 'VBP')
VBG ('hawking', 'VBG')
VBD ('claimed', 'VBD')
VBP ('exist', 'VBP')
VB ('have', 'VB')
VBD ('had', 'VBD')
VB ('do', 'VB')
VBD ('popped', 'VBD')
VBD ('inflated', 'VBD')
VBD ('doubled',

JJ ('difficult', 'JJ')
JJ ('difficult', 'JJ')
JJ ('imaginative', 'JJ')
JJ ('open', 'JJ')
JJ ('entire', 'JJ')
JJ ('human', 'JJ')
JJ ('aftermath', 'JJ')
JJ ('beautiful', 'JJ')
JJ ('possible', 'JJ')
JJ ('wonderful', 'JJ')
JJ ('easy', 'JJ')
JJ ('wonderful', 'JJ')
JJ ('major', 'JJ')
JJ ('i', 'JJ')
JJ ('i', 'JJ')
JJ ('next', 'JJ')
JJ ('good', 'JJ')
JJ ('easy', 'JJ')
JJ ('simple', 'JJ')
JJ ('many', 'JJ')
JJ ('new', 'JJ')
JJ ('interesting', 'JJ')
JJ ('great', 'JJ')
JJ ('amazon', 'JJ')
JJ ('aristotle', 'JJ')
JJ ('basic', 'JJ')
JJ ('universe', 'JJ')
JJ ('basic', 'JJ')
JJ ('english', 'JJ')
JJ ('plus', 'JJ')
JJ ('only', 'JJ')
JJ ('famous', 'JJ')
JJR ('easier', 'JJR')
JJ ('genius', 'JJ')
JJ ('plz', 'JJ')
JJ ('first', 'JJ')
JJ ('legendary', 'JJ')
JJ ('beautiful', 'JJ')
JJ ('readersthis', 'JJ')
JJ ('youre', 'JJ')
JJ ('small', 'JJ')
JJ ('physic', 'JJ')
JJ ('moderate', 'JJ')
JJ ('great', 'JJ')
JJ ('wa', 'JJ')
JJ ('good', 'JJ')
JJ ('bad', 'JJ')
JJ ('light', 'JJ')
JJ ('affordable', 'JJ')
JJ ('abstract', 

JJ ('curious', 'JJ')
JJ ('universeawsm', 'JJ')
JJ ('brief', 'JJ')
JJ ('complete', 'JJ')
JJ ('universe', 'JJ')
JJ ('great', 'JJ')
JJ ('big', 'JJ')
JJ ('everythingthe', 'JJ')
JJ ('same', 'JJ')
JJ ('physic', 'JJ')
JJ ('natural', 'JJ')
JJ ('u', 'JJ')
JJ ('great', 'JJ')
JJ ('such', 'JJ')
JJ ('easy', 'JJ')
JJ ('open', 'JJ')
JJ ('normal', 'JJ')
JJ ('good', 'JJ')
JJ ('great', 'JJ')
JJ ('bad', 'JJ')
JJ ('hard', 'JJ')
JJ ('affordable', 'JJ')
JJ ('kindle', 'JJ')
JJ ('good', 'JJ')
JJ ('pirated', 'JJ')
JJ ('poor', 'JJ')
JJ ('quality', 'JJ')
JJ ('nice', 'JJ')
JJ ('laden', 'JJ')
JJ ('scientific', 'JJ')
JJR ('more', 'JJR')
JJ ('i', 'JJ')
JJ ('spiritual', 'JJ')
JJ ('great', 'JJ')
JJ ('intellectual', 'JJ')
JJS ('best', 'JJS')
JJ ('popular', 'JJ')
JJ ('wa', 'JJ')
JJ ('excellent', 'JJ')
JJ ('good', 'JJ')
JJ ('i', 'JJ')
JJ ('i', 'JJ')
JJ ('basic', 'JJ')
JJ ('capable', 'JJ')
JJ ('exhaustive', 'JJ')
JJ ('interested', 'JJ')
JJ ('physic', 'JJ')
JJ ('good', 'JJ')
JJS ('best', 'JJS')
JJ ('wonderful', 'JJ')
JJ ('

JJ ('informative', 'JJ')
JJ ('excellent', 'JJ')
JJ ('good', 'JJ')
JJR ('better', 'JJR')
JJ ('nice', 'JJ')
JJ ('good', 'JJ')
JJ ('good', 'JJ')
JJ ('good', 'JJ')
JJ ('good', 'JJ')
JJ ('good', 'JJ')
JJ ('good', 'JJ')
JJ ('poor', 'JJ')
JJ ('good', 'JJ')
JJ ('nice', 'JJ')
JJ ('such', 'JJ')
JJ ('awesome', 'JJ')
JJ ('quite', 'JJ')
JJ ('old', 'JJ')
JJ ('awesome', 'JJ')
JJ ('good', 'JJ')
JJ ('poor', 'JJ')
JJ ('nice', 'JJ')
JJ ('amazing', 'JJ')
JJ ('good', 'JJ')
JJ ('great', 'JJ')
JJ ('good', 'JJ')
JJ ('great', 'JJ')
JJ ('great', 'JJ')
JJ ('knowledgeble', 'JJ')
JJ ('third', 'JJ')
JJ ('yellowish', 'JJ')
JJ ('good', 'JJ')
JJ ('nice', 'JJ')
JJ ('nice', 'JJ')
JJ ('favourite', 'JJ')
JJS ('best', 'JJS')
JJ ('awesome', 'JJ')
JJ ('excellent', 'JJ')
JJS ('best', 'JJS')
JJ ('awesome', 'JJ')
JJS ('best', 'JJS')
JJ ('great', 'JJ')
JJ ('fine', 'JJ')
JJ ('great', 'JJ')
JJ ('clear', 'JJ')
JJS ('best', 'JJS')
JJ ('good', 'JJ')
JJS ('best', 'JJS')
JJ ('st', 'JJ')
JJ ('wonderful', 'JJ')
JJ ('great', 'JJ')
JJ ('pa

JJR ('more', 'JJR')
JJ ('bible', 'JJ')
JJ ('enigmatic', 'JJ')
JJ ('physical', 'JJ')
JJ ('many', 'JJ')
JJ ('universe', 'JJ')
JJ ('same', 'JJ')
JJ ('same', 'JJ')
JJ ('many', 'JJ')
JJ ('little', 'JJ')
JJ ('complex', 'JJ')
JJ ('complex', 'JJ')
JJ ('entire', 'JJ')
JJ ('interesting', 'JJ')
JJ ('familiar', 'JJ')
JJ ('equal', 'JJ')
JJ ('worldfamous', 'JJ')
JJ ('many', 'JJ')
JJ ('autobiographical', 'JJ')
JJ ('basic', 'JJ')
JJ ('i', 'JJ')
JJ ('final', 'JJ')
JJ ('casual', 'JJ')
JJ ('absolute', 'JJ')
JJ ('i', 'JJ')
JJ ('wa', 'JJ')
JJ ('different', 'JJ')
JJ ('different', 'JJ')
JJ ('brief', 'JJ')
JJ ('i', 'JJ')
JJ ('many', 'JJ')
JJ ('new', 'JJ')
JJR ('le', 'JJR')
JJ ('relative', 'JJ')
JJ ('exact', 'JJ')
JJ ('famous', 'JJ')
JJ ('black', 'JJ')
JJ ('interesting', 'JJ')
JJ ('entire', 'JJ')
JJ ('same', 'JJ')
JJ ('same', 'JJ')
JJ ('black', 'JJ')
JJ ('black', 'JJ')
JJ ('black', 'JJ')
JJ ('used', 'JJ')
JJS ('most', 'JJS')
JJ ('favourite', 'JJ')
JJ ('brilliant', 'JJ')
JJ ('such', 'JJ')
JJ ('simple', 'JJ')
JJ

WRB ('how', 'WRB')
WRB ('where', 'WRB')
RB ('just', 'RB')
RB ('not', 'RB')
RB ('just', 'RB')
RB ('very', 'RB')
RB ('ever', 'RB')
RB ('only', 'RB')
RB ('once', 'RB')
RB ('unexpectedly', 'RB')
RB ('immediately', 'RB')
RB ('not', 'RB')
RB ('always', 'RB')
RB ('too', 'RB')
RB ('enough', 'RB')
RB ('purely', 'RB')
RB ('just', 'RB')
RB ('very', 'RB')
WRB ('when', 'WRB')
RB ('just', 'RB')
RB ('here', 'RB')
RB ('then', 'RB')
RB ('i', 'RB')
RB ('just', 'RB')
RB ('truly', 'RB')
RB ('absolutely', 'RB')
RB ('very', 'RB')
RB ('very', 'RB')
RB ('definitely', 'RB')
RB ('then', 'RB')
RB ('very', 'RB')
RB ('well', 'RB')
RB ('just', 'RB')
WRB ('wa', 'WRB')
RB ('twice', 'RB')
RB ('before', 'RB')
RB ('then', 'RB')
RB ('highly', 'RB')
RB ('easily', 'RB')
RB ('there', 'RB')
RB ('inside', 'RB')
RB ('even', 'RB')
RB ('exactly', 'RB')
WRB ('when', 'WRB')
RB ('long', 'RB')
RB ('ago', 'RB')
RB ('not', 'RB')
RB ('somehow', 'RB')
RB ('definitely', 'RB')
RB ('very', 'RB')
RB ('yet', 'RB')
RB ('nicely', 'RB')
RB ('ab

RB ('very', 'RB')
RB ('very', 'RB')
RB ('ever', 'RB')
RB ('very', 'RB')
RB ('very', 'RB')
RB ('very', 'RB')
RB ('very', 'RB')
RB ('not', 'RB')
RB ('very', 'RB')
RB ('awkward', 'RB')
RB ('very', 'RB')
RB ('very', 'RB')
RB ('very', 'RB')
RBS ('best', 'RBS')
RB ('once', 'RB')
RB ('non', 'RB')
RB ('ever', 'RB')
RB ('lot', 'RB')
RB ('very', 'RB')
RB ('v', 'RB')
RB ('just', 'RB')
RB ('also', 'RB')
RB ('very', 'RB')
RBR ('better', 'RBR')
RB ('not', 'RB')
RB ('ever', 'RB')
RB ('really', 'RB')
RB ('well', 'RB')
RB ('ever', 'RB')
RB ('very', 'RB')
RB ('very', 'RB')
RB ('not', 'RB')
RB ('very', 'RB')
RB ('nicely', 'RB')
RB ('very', 'RB')
RB ('very', 'RB')
RB ('very', 'RB')
RB ('seriously', 'RB')
RB ('very', 'RB')
RB ('very', 'RB')
RB ('very', 'RB')
RB ('not', 'RB')
RB ('very', 'RB')
RB ('easily', 'RB')
RB ('really', 'RB')
RB ('clearly', 'RB')
RB ('really', 'RB')
RB ('thus', 'RB')
RB ('not', 'RB')
RB ('just', 'RB')
RB ('very', 'RB')
RB ('amazingly', 'RB')
RB ('very', 'RB')
RB ('only', 'RB')
RB ('u

WP ('what', 'WP')
PRP ('he', 'PRP')
PRP ('he', 'PRP')
WP ('who', 'WP')
PRP ('he', 'PRP')
PRP$ ('our', 'PRP$')
PRP ('we', 'PRP')
PRP ('he', 'PRP')
PRP$ ('our', 'PRP$')
PRP$ ('his', 'PRP$')
PRP ('he', 'PRP')
WP ('who', 'WP')
PRP ('themselves', 'PRP')
PRP ('it', 'PRP')
WP ('who', 'WP')
PRP ('you', 'PRP')
PRP ('you', 'PRP')
PRP ('you', 'PRP')
PRP ('you', 'PRP')
PRP ('you', 'PRP')
PRP$ ('my', 'PRP$')
WP ('what', 'WP')
WP ('what', 'WP')
PRP$ ('my', 'PRP$')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
PRP ('me', 'PRP')
PRP ('them', 'PRP')
PRP ('you', 'PRP')
PRP$ ('our', 'PRP$')
PRP ('me', 'PRP')
PRP ('me', 'PRP')
PRP ('me', 'PRP')
PRP ('it', 'PRP')
PRP ('you', 'PRP')
PRP ('it', 'PRP')
PRP ('you', 'PRP')
PRP ('you', 'PRP')
PRP ('it', 'PRP')
PRP ('you', 'PRP')
PRP ('you', 'PRP')
PRP ('you', 'PRP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
PRP ('we', 'PRP')
WP ('who', 'WP')
PRP ('you', 'PRP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
PRP ('you', 'PRP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
WP ('what', 'WP')
PRP ('it',

PRP ('it', 'PRP')
PRP ('it', 'PRP')
WP ('what', 'WP')
PRP ('you', 'PRP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
PRP ('you', 'PRP')
PRP ('it', 'PRP')
PRP$ ('your', 'PRP$')
PRP$ ('my', 'PRP$')
PRP ('it', 'PRP')
PRP ('he', 'PRP')
PRP ('me', 'PRP')
PRP ('it', 'PRP')
WP ('who', 'WP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
WP ('what', 'WP')
PRP ('you', 'PRP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
PRP ('you', 'PRP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
WP ('who', 'WP')
PRP ('it', 'PRP')
PRP$ ('our', 'PRP$')
PRP ('we', 'PRP')
PRP ('it', 'PRP')
PRP ('we', 'PRP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
PRP ('me', 'PRP')
PRP ('me', 'PRP')
PRP ('you', 'PRP')
PRP ('you', 'PRP')
PRP ('them', 'PRP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
PRP$ ('my', 'PRP$')
WP ('what', 'WP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
PRP ('it', 'PRP')
WP ('what', 'WP')
PRP ('we', 'PRP')
PRP ('we', 'PRP')
WP ('what', 'WP')
PRP ('we', 'PRP')
PRP ('it', 

review  noun_count  verb_count  \
0  what did god do before he created the universe...          45          30   
1  a very good bookthis book is like a treeyou ca...          16          13   
2  there is no comparison of this book from the b...          16           9   
3  a brief history of time what a fascinating boo...          44          27   
4  this book is really a proof that why wa stephe...          26          21   

   adj_count  adv_count  pron_count  
0         17          9          15  
1          3          7           5  
2          5          3           1  
3         21          7          12  
4         12          5           9

In [18]:
data.head()

review  word_count  char_count  \
0  what did god do before he created the universe...         180        1019   
1  a very good bookthis book is like a treeyou ca...          70         362   
2  there is no comparison of this book from the b...          56         314   
3  a brief history of time what a fascinating boo...         162         915   
4  this book is really a proof that why wa stephe...         106         577   

   avg_word  stopwords  hastags  numerics  upper  noun_count  verb_count  \
0  4.666667         87        0         0      0          45          30   
1  4.185714         38        0         0      0          16          13   
2  4.625000         28        0         0      0          16           9   
3  4.654321         79        0         0      0          44          27   
4  4.452830         50        0         0      0          26          21   

   adj_count  adv_count  pron_count  
0         17          9          15  
1          3          7           5  
2          5          3           1  
3         21          7          12  
4         12          5           9

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [20]:
cv=CountVectorizer()
A_vec = cv.fit_transform(new_review)
print(A_vec.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [21]:
tv=TfidfVectorizer()
t_vec = tv.fit_transform(new_review)
print(t_vec.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [22]:
feature_names = tv.get_feature_names()

dense = t_vec.todense()
denselist = dense.tolist()
daf = pd.DataFrame(denselist, columns=feature_names)

In [23]:
feature_names

['abbreviated',
 'able',
 'about',
 'above',
 'absence',
 'absolute',
 'absolutely',
 'abstract',
 'abysmally',
 'academic',
 'accelerator',
 'acceptable',
 'accepted',
 'accessible',
 'accidentally',
 'accompanying',
 'according',
 'accordinglythanks',
 'account',
 'achievement',
 'acquaintance',
 'across',
 'actual',
 'actually',
 'add',
 'added',
 'addictiveyou',
 'addressed',
 'adept',
 'administration',
 'advance',
 'aeronautics',
 'affordable',
 'african',
 'after',
 'aftermath',
 'again',
 'against',
 'age',
 'ago',
 'ahould',
 'aid',
 'aimed',
 'aint',
 'airplane',
 'al',
 'albert',
 'alert',
 'alive',
 'alived',
 'all',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'amateur',
 'amaze',
 'amazed',
 'amazing',
 'amazingbook',
 'amazingly',
 'amazon',
 'amazonabout',
 'amazonpaper',
 'amazonwaiting',
 'ammezing',
 'amount',
 'amthink',
 'amusing',
 'an',
 'analogy',
 'analysis',
 'ancient',
 'and',
 'andfont',
 'angry',
 'another',
 'answer',
 'answered

In [24]:
df_c =pd.concat([daf,data], axis=1)
df_c.head()

abbreviated  able     about  above  absence  absolute  absolutely  \
0          0.0   0.0  0.000000    0.0      0.0       0.0         0.0   
1          0.0   0.0  0.000000    0.0      0.0       0.0         0.0   
2          0.0   0.0  0.000000    0.0      0.0       0.0         0.0   
3          0.0   0.0  0.145670    0.0      0.0       0.0         0.0   
4          0.0   0.0  0.062066    0.0      0.0       0.0         0.0   

   abstract  abysmally  academic  ...  avg_word  stopwords  hastags  numerics  \
0       0.0        0.0       0.0  ...  4.666667         87        0         0   
1       0.0        0.0       0.0  ...  4.185714         38        0         0   
2       0.0        0.0       0.0  ...  4.625000         28        0         0   
3       0.0        0.0       0.0  ...  4.654321         79        0         0   
4       0.0        0.0       0.0  ...  4.452830         50        0         0   

   upper  noun_count  verb_count  adj_count  adv_count  pron_count  
0      0          45          30         17          9          15  
1      0          16          13          3          7           5  
2      0          16           9          5          3           1  
3      0          44          27         21          7          12  
4      0          26          21         12          5           9  

[5 rows x 2179 columns]